// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/test.proto

/*
Package txwx is a generated protocol buffer package.

It is generated from these files:
	proto/test.proto

It has these top-level messages:
	WeatherMessage
*/
package txwx

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WeatherMessage_Type int32

const (
	WeatherMessage_METAR WeatherMessage_Type = 0
	WeatherMessage_TAF   WeatherMessage_Type = 1
)

var WeatherMessage_Type_name = map[int32]string{
	0: "METAR",
	1: "TAF",
}
var WeatherMessage_Type_value = map[string]int32{
	"METAR": 0,
	"TAF":   1,
}

func (x WeatherMessage_Type) String() string {
	return proto.EnumName(WeatherMessage_Type_name, int32(x))
}
func (WeatherMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type WeatherMessage struct {
	Type       WeatherMessage_Type `protobuf:"varint,1,opt,name=type,enum=txwx.WeatherMessage_Type" json:"type,omitempty"`
	TxTime     uint32              `protobuf:"varint,2,opt,name=tx_time,json=txTime" json:"tx_time,omitempty"`
	StationLat float32             `protobuf:"fixed32,3,opt,name=station_lat,json=stationLat" json:"station_lat,omitempty"`
	StationLng float32             `protobuf:"fixed32,4,opt,name=station_lng,json=stationLng" json:"station_lng,omitempty"`
	TextData   string              `protobuf:"bytes,10,opt,name=text_data,json=textData" json:"text_data,omitempty"`
}

func (m *WeatherMessage) Reset()                    { *m = WeatherMessage{} }
func (m *WeatherMessage) String() string            { return proto.CompactTextString(m) }
func (*WeatherMessage) ProtoMessage()               {}
func (*WeatherMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WeatherMessage) GetType() WeatherMessage_Type {
	if m != nil {
		return m.Type
	}
	return WeatherMessage_METAR
}

func (m *WeatherMessage) GetTxTime() uint32 {
	if m != nil {
		return m.TxTime
	}
	return 0
}

func (m *WeatherMessage) GetStationLat() float32 {
	if m != nil {
		return m.StationLat
	}
	return 0
}

func (m *WeatherMessage) GetStationLng() float32 {
	if m != nil {
		return m.StationLng
	}
	return 0
}

func (m *WeatherMessage) GetTextData() string {
	if m != nil {
		return m.TextData
	}
	return ""
}

func init() {
	proto.RegisterType((*WeatherMessage)(nil), "txwx.WeatherMessage")
	proto.RegisterEnum("txwx.WeatherMessage_Type", WeatherMessage_Type_name, WeatherMessage_Type_value)
}

func init() { proto.RegisterFile("proto/test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xcf, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x71, 0xb7, 0x8d, 0xad, 0x19, 0xb1, 0x84, 0xbd, 0xb8, 0xea, 0xc1, 0xd0, 0xd3, 0x5e,
	0x5c, 0x41, 0x9f, 0xa0, 0xa0, 0x9e, 0xec, 0x65, 0x59, 0xf0, 0x18, 0x46, 0x1c, 0x62, 0xc0, 0x26,
	0xa1, 0xfb, 0x81, 0x9b, 0xe7, 0xf4, 0x85, 0x24, 0xa1, 0x97, 0xdc, 0x86, 0x3f, 0xbf, 0xc3, 0x7c,
	0x54, 0xf4, 0xc7, 0x0e, 0xdd, 0x23, 0x24, 0xc2, 0x4d, 0xa7, 0xce, 0x90, 0x7e, 0xd3, 0xf6, 0x4f,
	0xd1, 0xe6, 0x43, 0x18, 0xdf, 0x72, 0xdc, 0x4b, 0x8c, 0x5c, 0x8b, 0x7e, 0xa0, 0x0c, 0x43, 0x2f,
	0x46, 0x95, 0xca, 0x6e, 0x9e, 0x6e, 0xdc, 0xe8, 0xdc, 0xdc, 0xb8, 0x30, 0xf4, 0xe2, 0x27, 0xa6,
	0xaf, 0x69, 0x8d, 0x54, 0xa1, 0x39, 0x88, 0x59, 0x94, 0xca, 0x5e, 0xf9, 0x15, 0x52, 0x68, 0x0e,
	0xa2, 0xef, 0xe9, 0x32, 0x82, 0xd1, 0x74, 0x6d, 0xf5, 0xc3, 0x30, 0xcb, 0x52, 0xd9, 0x85, 0xa7,
	0x53, 0x7a, 0x67, 0xcc, 0x40, 0x5b, 0x9b, 0x6c, 0x0e, 0xda, 0x5a, 0xdf, 0x51, 0x0e, 0x49, 0xa8,
	0xbe, 0x18, 0x6c, 0xa8, 0x54, 0x36, 0xf7, 0x17, 0x63, 0x78, 0x61, 0xf0, 0xf6, 0x96, 0xb2, 0xf1,
	0x0b, 0x9d, 0xd3, 0xf9, 0xfe, 0x35, 0xec, 0x7c, 0x71, 0xa6, 0xd7, 0xb4, 0x0c, 0xbb, 0xb7, 0x42,
	0x7d, 0xae, 0xa6, 0x89, 0xcf, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xa1, 0x99, 0x28, 0xf6,
	0x00, 0x00, 0x00,
}
