// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/test.proto

package txwx

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WeatherMessage_Type int32

const (
	WeatherMessage_METAR  WeatherMessage_Type = 0
	WeatherMessage_TAF    WeatherMessage_Type = 1
	WeatherMessage_BEACON WeatherMessage_Type = 2
)

var WeatherMessage_Type_name = map[int32]string{
	0: "METAR",
	1: "TAF",
	2: "BEACON",
}

var WeatherMessage_Type_value = map[string]int32{
	"METAR":  0,
	"TAF":    1,
	"BEACON": 2,
}

func (x WeatherMessage_Type) String() string {
	return proto.EnumName(WeatherMessage_Type_name, int32(x))
}

func (WeatherMessage_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fc70169f84046e97, []int{0, 0}
}

type WeatherMessage struct {
	Type                 WeatherMessage_Type `protobuf:"varint,1,opt,name=type,proto3,enum=txwx.WeatherMessage_Type" json:"type,omitempty"`
	TxTime               uint32              `protobuf:"varint,2,opt,name=tx_time,json=txTime,proto3" json:"tx_time,omitempty"`
	StationLat           float32             `protobuf:"fixed32,3,opt,name=station_lat,json=stationLat,proto3" json:"station_lat,omitempty"`
	StationLng           float32             `protobuf:"fixed32,4,opt,name=station_lng,json=stationLng,proto3" json:"station_lng,omitempty"`
	ObservationTime      uint32              `protobuf:"varint,5,opt,name=observation_time,json=observationTime,proto3" json:"observation_time,omitempty"`
	TextData             string              `protobuf:"bytes,10,opt,name=text_data,json=textData,proto3" json:"text_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WeatherMessage) Reset()         { *m = WeatherMessage{} }
func (m *WeatherMessage) String() string { return proto.CompactTextString(m) }
func (*WeatherMessage) ProtoMessage()    {}
func (*WeatherMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_fc70169f84046e97, []int{0}
}

func (m *WeatherMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WeatherMessage.Unmarshal(m, b)
}
func (m *WeatherMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WeatherMessage.Marshal(b, m, deterministic)
}
func (m *WeatherMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WeatherMessage.Merge(m, src)
}
func (m *WeatherMessage) XXX_Size() int {
	return xxx_messageInfo_WeatherMessage.Size(m)
}
func (m *WeatherMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_WeatherMessage.DiscardUnknown(m)
}

var xxx_messageInfo_WeatherMessage proto.InternalMessageInfo

func (m *WeatherMessage) GetType() WeatherMessage_Type {
	if m != nil {
		return m.Type
	}
	return WeatherMessage_METAR
}

func (m *WeatherMessage) GetTxTime() uint32 {
	if m != nil {
		return m.TxTime
	}
	return 0
}

func (m *WeatherMessage) GetStationLat() float32 {
	if m != nil {
		return m.StationLat
	}
	return 0
}

func (m *WeatherMessage) GetStationLng() float32 {
	if m != nil {
		return m.StationLng
	}
	return 0
}

func (m *WeatherMessage) GetObservationTime() uint32 {
	if m != nil {
		return m.ObservationTime
	}
	return 0
}

func (m *WeatherMessage) GetTextData() string {
	if m != nil {
		return m.TextData
	}
	return ""
}

func init() {
	proto.RegisterEnum("txwx.WeatherMessage_Type", WeatherMessage_Type_name, WeatherMessage_Type_value)
	proto.RegisterType((*WeatherMessage)(nil), "txwx.WeatherMessage")
}

func init() { proto.RegisterFile("proto/test.proto", fileDescriptor_fc70169f84046e97) }

var fileDescriptor_fc70169f84046e97 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0xd0, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x06, 0x60, 0xdb, 0xed, 0x76, 0xed, 0x88, 0x6b, 0xc8, 0xc5, 0x88, 0x07, 0x65, 0x0f, 0xa2,
	0x07, 0x2b, 0xe8, 0x13, 0x54, 0x5d, 0x4f, 0xae, 0x42, 0x28, 0x78, 0x2c, 0x59, 0x1c, 0xea, 0x82,
	0xb6, 0xa5, 0xf9, 0xd1, 0xf8, 0x0a, 0x3e, 0xb5, 0x69, 0xf4, 0xb0, 0xbd, 0x65, 0xfe, 0x7c, 0xe1,
	0x0f, 0x43, 0xa2, 0xeb, 0x5b, 0xb4, 0x57, 0x60, 0x8b, 0x3c, 0x1c, 0x65, 0x02, 0xf7, 0xe5, 0x16,
	0x3f, 0x31, 0xcd, 0x5f, 0xd8, 0xe0, 0x8d, 0xfb, 0x15, 0x5b, 0x6b, 0x6a, 0x96, 0x97, 0x94, 0xe0,
	0xbb, 0x63, 0x15, 0x9d, 0x46, 0xe7, 0xf3, 0xeb, 0xa3, 0x7c, 0x70, 0xf9, 0xd8, 0xe4, 0xa5, 0x07,
	0x3a, 0x30, 0x79, 0x48, 0x33, 0xb8, 0x0a, 0x9b, 0x0f, 0x56, 0xb1, 0x7f, 0xb1, 0xaf, 0x53, 0xb8,
	0xd2, 0x4f, 0xf2, 0x84, 0xf6, 0x2c, 0x0c, 0x36, 0x6d, 0x53, 0xbd, 0x1b, 0xa8, 0x89, 0xbf, 0x8c,
	0x35, 0xfd, 0x47, 0x8f, 0x06, 0x23, 0xd0, 0xd4, 0x2a, 0x19, 0x83, 0xa6, 0x96, 0x17, 0x24, 0xda,
	0xb5, 0xe5, 0xfe, 0xf3, 0x0f, 0x85, 0x8e, 0x69, 0xe8, 0x38, 0xd8, 0xca, 0x43, 0xd9, 0x31, 0x65,
	0x60, 0x87, 0xea, 0xd5, 0xc0, 0x28, 0xf2, 0x26, 0xd3, 0xbb, 0x43, 0x70, 0xef, 0xe7, 0xc5, 0x19,
	0x25, 0xc3, 0x87, 0x65, 0x46, 0xd3, 0xd5, 0xb2, 0x2c, 0xb4, 0xd8, 0x91, 0x33, 0x9a, 0x94, 0xc5,
	0x83, 0x88, 0x24, 0x51, 0x7a, 0xbb, 0x2c, 0xee, 0x9e, 0x9f, 0x44, 0xbc, 0x4e, 0xc3, 0x66, 0x6e,
	0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xca, 0xff, 0x65, 0x5c, 0x2d, 0x01, 0x00, 0x00,
}
