// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/test.proto

/*
Package txwx is a generated protocol buffer package.

It is generated from these files:
	proto/test.proto

It has these top-level messages:
	WeatherMessage
*/
package txwx

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WeatherMessage_Type int32

const (
	WeatherMessage_METAR WeatherMessage_Type = 0
	WeatherMessage_TAF   WeatherMessage_Type = 1
)

var WeatherMessage_Type_name = map[int32]string{
	0: "METAR",
	1: "TAF",
}
var WeatherMessage_Type_value = map[string]int32{
	"METAR": 0,
	"TAF":   1,
}

func (x WeatherMessage_Type) String() string {
	return proto.EnumName(WeatherMessage_Type_name, int32(x))
}
func (WeatherMessage_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type WeatherMessage struct {
	Type            WeatherMessage_Type `protobuf:"varint,1,opt,name=type,enum=txwx.WeatherMessage_Type" json:"type,omitempty"`
	TxTime          uint32              `protobuf:"varint,2,opt,name=tx_time,json=txTime" json:"tx_time,omitempty"`
	StationLat      float32             `protobuf:"fixed32,3,opt,name=station_lat,json=stationLat" json:"station_lat,omitempty"`
	StationLng      float32             `protobuf:"fixed32,4,opt,name=station_lng,json=stationLng" json:"station_lng,omitempty"`
	ObservationTime uint32              `protobuf:"varint,5,opt,name=observation_time,json=observationTime" json:"observation_time,omitempty"`
	TextData        string              `protobuf:"bytes,10,opt,name=text_data,json=textData" json:"text_data,omitempty"`
}

func (m *WeatherMessage) Reset()                    { *m = WeatherMessage{} }
func (m *WeatherMessage) String() string            { return proto.CompactTextString(m) }
func (*WeatherMessage) ProtoMessage()               {}
func (*WeatherMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WeatherMessage) GetType() WeatherMessage_Type {
	if m != nil {
		return m.Type
	}
	return WeatherMessage_METAR
}

func (m *WeatherMessage) GetTxTime() uint32 {
	if m != nil {
		return m.TxTime
	}
	return 0
}

func (m *WeatherMessage) GetStationLat() float32 {
	if m != nil {
		return m.StationLat
	}
	return 0
}

func (m *WeatherMessage) GetStationLng() float32 {
	if m != nil {
		return m.StationLng
	}
	return 0
}

func (m *WeatherMessage) GetObservationTime() uint32 {
	if m != nil {
		return m.ObservationTime
	}
	return 0
}

func (m *WeatherMessage) GetTextData() string {
	if m != nil {
		return m.TextData
	}
	return ""
}

func init() {
	proto.RegisterType((*WeatherMessage)(nil), "txwx.WeatherMessage")
	proto.RegisterEnum("txwx.WeatherMessage_Type", WeatherMessage_Type_name, WeatherMessage_Type_value)
}

func init() { proto.RegisterFile("proto/test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 228 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x71, 0xb7, 0x4d, 0x5b, 0x33, 0x62, 0x0d, 0x7b, 0x71, 0xd5, 0x83, 0xa1, 0xa7, 0x78,
	0x30, 0x82, 0x3e, 0x41, 0x41, 0x3d, 0xd9, 0xcb, 0x12, 0xf0, 0x18, 0xa6, 0x38, 0xc4, 0x80, 0x4d,
	0x42, 0xf6, 0x43, 0x37, 0x2f, 0x2f, 0x92, 0xd5, 0x83, 0xb9, 0x2d, 0x1f, 0x3f, 0xf8, 0x2f, 0x43,
	0x49, 0xd7, 0xb7, 0x68, 0xef, 0x20, 0x0e, 0x79, 0x78, 0xea, 0x08, 0xfe, 0xcb, 0x6f, 0xbe, 0x15,
	0xad, 0x5f, 0x85, 0xf1, 0x2e, 0xfd, 0x4e, 0x9c, 0xe3, 0x4a, 0xf4, 0x2d, 0x45, 0x18, 0x3a, 0x31,
	0x2a, 0x55, 0xd9, 0xfa, 0xfe, 0x22, 0x1f, 0x5d, 0x3e, 0x35, 0x79, 0x31, 0x74, 0x62, 0x03, 0xd3,
	0xe7, 0xb4, 0x82, 0x2f, 0x51, 0x1f, 0xc4, 0xcc, 0x52, 0x95, 0x9d, 0xda, 0x25, 0x7c, 0x51, 0x1f,
	0x44, 0x5f, 0xd3, 0x89, 0x03, 0xa3, 0x6e, 0x9b, 0xf2, 0x83, 0x61, 0xe6, 0xa9, 0xca, 0x66, 0x96,
	0xfe, 0xa6, 0x17, 0xc6, 0x04, 0x34, 0x95, 0x89, 0xa6, 0xa0, 0xa9, 0xf4, 0x0d, 0x25, 0xed, 0xde,
	0x49, 0xff, 0xf9, 0x8b, 0x42, 0x63, 0x11, 0x1a, 0x67, 0xff, 0xf6, 0x10, 0xbb, 0xa2, 0x18, 0xe2,
	0x51, 0xbe, 0x31, 0xd8, 0x50, 0xaa, 0xb2, 0xd8, 0x1e, 0x8f, 0xc3, 0x23, 0x83, 0x37, 0x97, 0x14,
	0x8d, 0x1f, 0xd6, 0x31, 0x2d, 0x76, 0x4f, 0xc5, 0xd6, 0x26, 0x47, 0x7a, 0x45, 0xf3, 0x62, 0xfb,
	0x9c, 0xa8, 0xfd, 0x32, 0x5c, 0xe3, 0xe1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x00, 0x10, 0xea, 0x9b,
	0x21, 0x01, 0x00, 0x00,
}
